### ISSUE TITLE
error getting metadata with a fresh 1.9 script install

### ISSUE THREAD

**Issue by satsukiyatoshi** [Kayomani/PlexExternalPlayer#10]
Hello.
I've done a full fresh install of the 1.9 script and now have the play externaly button at the top right of the movie description.

but now i get this error:
![screenshot006](https://cloud.githubusercontent.com/assets/8547498/23972579/ab245610-09d2-11e7-9cfa-4ccda707ba86.png)
i tryed older scripts versions and i get this error for all scripts above the 1.4 version

thanks again

**Comment by Kayomani** [comment]
Can you grab 1.11 and look in the console (F12) and see if it says anything?

You are running the latest tray agent right?

**Comment by satsukiyatoshi** [comment]
Hello

yes i use 1.8 agent

here's the log :


"[Plex External] Error getting metadata from http://192.168.1.199:32400/library/metadata/437?checkFiles=1&includeExtras=1Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"  index.html%20line%203%20%3E%20Function:68:5
[Plex External] Error {}  index.html%20line%203%20%3E%20Function:68:5
"[Companion] Opening long poll to beast666 at http://192.168.1.199:32400/player/proxy/poll"  main.3effcbaef0fd951124cd.js:2444:426
Erreur d’analyse XML : aucun élément trouvé
Emplacement : http://192.168.1.199:32400/player/proxy/poll?deviceClass=pc&protocolVersion=1&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1&X-Plex-Product=Plex%20Web&X-Plex-Version=3.0.1&X-Plex-Client-Identifier=2sokxeaw67j&X-Plex-Platform=Firefox&X-Plex-Platform-Version=51.0&X-Plex-Device=Windows&X-Plex-Device-Name=Plex%20Web%20%28Firefox%29&X-Plex-Device-Screen-Resolution=1757x973%2C1920x1080
Numéro de ligne 1, Colonne 1 :



________________________________
De : Kayomani <notifications@github.com>
Envoyé : mercredi 15 mars 2017 22:40
À : Kayomani/PlexExternalPlayer
Cc : satsukiyatoshi; Author
Objet : Re: [Kayomani/PlexExternalPlayer] error getting metadata with a fresh 1.9 script install (#10)


Can you grab 1.10 and look in the console (F12) and see if it says anything?

**Comment by caruga1012** [comment]
I have the same problem!

**Comment by Kayomani** [comment]
Hmm are you on the latest Plex?  version 1.4.4.3495

I've uploaded 1.12 but if you are missing those details it will not find your auth details unless you are the server owner.

If its still failing then go into the console and send me the results of running:

JSON.stringify(localStorage.users).replace(new RegExp('accessToken\\\\"\S*:\S*\\\\"[a-z,A-Z,0-9]+', "gm"),'accessToken\\\\":\\\\rem"\\\\"')

That should strip out your auth tokens from the result and either post the result here or email it to me at my name at gmail dot com.

**Comment by satsukiyatoshi** [comment]
1.12 works perfectly on all my computers.
Thanks !

**Comment by caruga1012** [comment]
v1.12 works!

thank you very much for a new version that works.
