### ISSUE TITLE
error getting metadata - TypeError: localStorage is null

### ISSUE THREAD

**Issue by Madeupname722** [Kayomani/PlexExternalPlayer#11]
This works perfect on one of my PC's. It turns Plex into exactly what I was looking for, a fancy library front end for VLC.

It won't work on my other, near identical, PC though. 

Plex External Player
Error getting metadata from
http://127.0.0.1:32400/library
/metadata/3?checkFiles=1&
includeExtras=1Error:TypeError:
localStorage is null

SOLVED: I finally noticed that the PC this wouldn't work on had  the 64bit version of Firefox installed and the one it did work on had the 32bit. So I reinstalled 32bit Firefox and the error is gone.

Apparently this doesn't work on64bit Firefox.

**Comment by Kayomani** [comment]
If you bring the console up does it say anything interesting?

**Comment by Madeupname722** [comment]
I just received notification of your reply this morning.

Switching to 32 bit Firefox solved my issue and I haven't tried using your addon with 64 bit since. 

As mozilla will be be automatically updating users Firefox to 64 bit soon, as well as disabling legacy addons, I hope you have the time to update your addon to keep it compatible.

For now, I am running two different versions of Firefox on that PC. Details on how to do so can be found in my post on the Mozilla forums.

https://support.mozilla.org/en-US/questions/1170758

**Comment by Kayomani** [comment]
I have only ever used 64bit and it works fine for me.  If you bring up the console does it say anything?

**Comment by Madeupname722** [comment]
I just installed "Plex-Media-Server-1.5.6.3790-4613ce077" and your addon "PlexExternalPlayerAgentInstall.v1.12.0" to my other PC "Win10 x64 Pro" that's running Firefox 52.3 64 bit ESR to see if I could reproduce the issue, and I can't.

I guess I'll credit this one to Gremlins. Thanks for answering.
