### ISSUE TITLE
Open Folder wont work

### ISSUE THREAD

**Issue by SkyAFS** [Kayomani/PlexExternalPlayer#14]
Ok, so, there is two buttons, Play externally and Open Folder, the open folder wont open folder, he does the same thing that the Play Externally does and play the movie. i think there is nothing wrong with my installation, is like this on purpose our its a bug? would be nice if i could access the folder from inside plex

**Comment by Kayomani** [comment]
Its working here, exactly where is the button you are clicking? A movie, a series etc? 

Also what does the console say? Push F12 - if you could paste that here taking out the bit after clientId that would be useful.

**Comment by SkyAFS** [comment]
im using firefox, with greasemonkey, the button wont work for me with series, anime our movies.

Just to be clear, i can watch, the movie opens on potplayer easy, what i cant is open the folder, he opens the movie on potplayer to.

by the way, when you are watching on external player this extension is supposed to mark as watched in plex to? 

i did not understand exactly about the console thing, i think is this
![2017-08-21_23-34-56](https://user-images.githubusercontent.com/16105922/29546226-64ca6186-86c9-11e7-80ed-dd7d4e5ba454.png)

**Comment by SkyAFS** [comment]
any news about this bug?

**Comment by Kayomani** [comment]
Fixed in 1.14

**Comment by SkyAFS** [comment]
thanks
