### ISSUE TITLE
Not working on Chrome...

### ISSUE THREAD

**Issue by Inrixia** [Kayomani/PlexExternalPlayer#16]
Works fine in firefox but not at all in chrome... No idea whats wrong :/

[![Screenshot from Gyazo](https://gyazo.com/595f20da1d492b6091647ed1a4479c01/raw)](https://gyazo.com/595f20da1d492b6091647ed1a4479c01)))

[![Screenshot from Gyazo](https://gyazo.com/bbf037ab87145a28a3c675afea532c9b/raw)](https://gyazo.com/bbf037ab87145a28a3c675afea532c9b)

**Comment by Inrixia** [comment]
Figured it out. Chrome just wont open 127.0.0.1, replacing that with localhost in the scripts fixes it. localhost also works fine for firefox so perhaps push a update sometime in the future with a simple Ctrl-F 127.0.0.1 and replace with localhost :)

**Comment by colepnc** [comment]
To add, this is still occurring. There's one line in the whole script (166) that refers to the server as 127.0.0.1 rather than localhost which breaks it. As soon as you change from 127.0.0.1 to localhost it works.

**Comment by Kayomani** [comment]
I find it strange that ipv4 loopback wouldn't work.  I have changed it to localhost for you.
