### ISSUE TITLE
Just wanna say thank you!

### ISSUE THREAD

**Issue by li0510** [Kayomani/PlexExternalPlayer#20]
So I just find ur post on plex form about an hour ago, then there I am. Have been tried both localhost&ddns, fortunately both are working perfect. (guess I will give up on samba on vpn or streaming which either restricts my network bandwidth or messes up anything)

One more thing is that can I forward ur tool to chinese form (I mean repost there with ur name and original link)? I guess many people there will need this useful tool like me. 

Anyway, thank you so much 👍

**Comment by Kayomani** [comment]
Glad you find it useful, feel free to forward it with link.  Is GitHub blocked where you are?

**Comment by li0510** [comment]
I do not think so. What’s up?
