### ISSUE TITLE
VLC 3.0.0 does not open on top

### ISSUE THREAD

**Issue by Madeupname722** [Kayomani/PlexExternalPlayer#21]
I'm running windows 10 home current, Firefox 55, Greasemonkey 3.11 and plex 3.2.1. Other than windows updates are disabled for the mentioned software. We only use plex for local media.

Since I updated VLC to 3.0 x64 the VLC window no longer open on top of other windows when opened from  within plex via this addon.

VLC 3.0 does open on top when opened directly.

**Comment by Kayomani** [comment]
Its an issue with VLC, the agent just tells windows to open the file which VLC picks up.  Due to that I can't pass any extra parameters to force it to open on top.  There will likely be an option relating to opening on top in the VLC options if not try a better player such as potplayer.
