### ISSUE TITLE
exclusive more failed.

### ISSUE THREAD

**Issue by chocoa510** [Kayomani/PlexExternalPlayer#26]
Hi
Firstly, great app!

System basics:
April update, Windows 10 64bit.
Nvidia driver 397.40
Running Plex Server on this PC -Playing files on this PC

I play mkv files via Plex Server via Chrome Browser +latest Tampermonkey script --> PlexExternalPlayer (v1.12.0.0)

I get an error from madVR "exclusive mode failed"  but file drops back to play windowed mode.
(I set automatic full-screen exclusive mode and Direct3d 11 in madVR to enable 10bit playback)

If I play the same file **direct** in MPC-HC  i don't get this error. i.e. the file plays in 10bit exclusive mode.

So,is something not being parsed to the player correctly?
Hope this makes sense. MY apologies if the issue lies elsewhere in the chain!- I'm no programmer!

Thanks!
chocoa

**Comment by chocoa510** [comment]
Hi
Did some testing and..
I **think** the issue is that the player does not have focus?

test:
In the above "failure" condition - ie file playing and "Full screen exclusive mode failed error", so playing in full screen _windowed_ mode instead. If I reload the file in MPC using key shortcut control + e, then the file reopens, this time in full screen exclusive mode as I needed!
 - The player has focus now because of the key shortcut used i suppose.

So, is this correct and it possible to set the focus to MPC when the file is passed to it?

Thanks!
Chocoa

**Comment by Kayomani** [comment]
Its entirely a mpc issue so this isn't the right place for support, i'd suggest disabling exclusive mode personally.
