### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by SashaCrow** [Kayomani/PlexExternalPlayer#27]
After updating Plex server to version 1.13.2.5154 your plugin stopped working, when you open a video or folder with files, the message "400 Bad Request"appears. Please update the plugin, it is simply irreplaceable and gorgeous.

**Comment by SashaCrow** [comment]
![2018-06-16_11-27-36](https://user-images.githubusercontent.com/40163412/41497150-69a87556-7158-11e8-9318-f7904b1dff15.png)

**Comment by Kayomani** [comment]
Fixed - update your userscript
