### ISSUE TITLE
Script not loading on Firefox/Chrome

### ISSUE THREAD

**Issue by Eleven0469** [Kayomani/PlexExternalPlayer#28]
I've installed the script from GreasyFork using Tampermonkey and Greasemonkey but neither show the script running when I visit the plex web page. Script is 1.16 and exe is 1.12 (tried 1.12 script but same thing).

**Comment by Kayomani** [comment]
If its not showing as active on the page then I guess your using a custom
url? You'll have to edit the script to include it.  Note you can't use the
plex.tv site but the direct address to your server.

**Comment by Eleven0469** [comment]
Thank you for such a quick reply! I wasn't using a custom url but your response did solve it. I was trying to use the plex.tv site instead of direct address, silly me. Works like a charm now!
