### ISSUE TITLE
Solved, user error

### ISSUE THREAD

**Issue by Almazick** [Kayomani/PlexExternalPlayer#29]
solved

**Comment by Kayomani** [comment]
Its working fine for me Tampermonkey 4.7 / Chrome 70.0.3538.77, is your chrome newer?

**Comment by M-RiC-French** [comment]
Hello,
I have the same problem with Plex 1.14.0.5465 + Firefox Quantum 63.0.3 (64 bits) + TamperMonkey 4.8.5847 and with Chrome 70.0.3538.102 + TamperMonkey 4.7.44. Did you find a solution ?

**Comment by M-RiC-French** [comment]
Works fine, I reinstalled PlexExternalPlayerAgentInstall.v1.12.0.exe from https://github.com/Kayomani/PlexExternalPlayer/releases
