### ISSUE TITLE
App doesn't launch if not using the master profile for the server

### ISSUE THREAD

**Issue by smarshallsay** [Kayomani/PlexExternalPlayer#3]
If I switch to another user, guest or another registered user with access on the server / HTPC machine the icons show to launch the external player but nothing happens when you click them (no messages)

Clicking link results in an HTTP 406 error (from console) also throws error in the error notification function (error is not defined)

VM138:77 Uncaught ReferenceError: error is not definedGM_xmlhttpRequest.onreadystatechange @ VM138:77(anonymous function) @ VM120:59
VM138:138 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagName' of null(…)

**Comment by Kayomani** [comment]
Switching users will not close the application and only one person can run it at a time on the same machine.  

I can look at stopping the server when you lock your session in the next version.

**Comment by smarshallsay** [comment]
Sorry I mean the main user inside Plex. If I change to either of the other
two accounts I have in Plex (a flatmate's Plex account or the guest
account) clicking the launch icon does nothing.

**Comment by smarshallsay** [comment]
I think I've solved the issue. I've forked your JS

**Comment by Kayomani** [comment]
Changes look good, could you make a pull request?

**Comment by Kayomani** [comment]
Fixed in the latest version.
