### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by tokoku** [Kayomani/PlexExternalPlayer#3]
Hi Kayomani can you help with the instalaltion of the agent?
Do I copy every  file within thw agent folder to the startup folder in my windows ?

Hope you can help me

Regards

**Comment by Kayomani** [comment]
Extract all the files in the zip to c:\apps\plexagent then create a shortcut to exe in your startup folder.

**Comment by tokoku** [comment]
so I create a shortcut in the startup folder, from a .exe file.? which .exe file? sorry for bothering you
