### ISSUE TITLE
Support the Hosted Plex Web App

### ISSUE THREAD

**Issue by cremor** [Kayomani/PlexExternalPlayer#31]
Could you please add support for running on https://app.plex.tv/desktop?

You'd have to get the server URL (like `https://<ip>.<hash>.plex.direct:32400`) from the API (https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=token should do the trick) and then use it instead of `window.location.origin`.

I've tried it in my local script with hardcoded URLs instead of the API call and it seems to work fine.

**Comment by cremor** [comment]
See #33 for additional required changes.

**Comment by Kayomani** [comment]
Certainly possible, it would need a bit of work though :)

**Comment by cremor** [comment]
Plex web version 3.106.1 needs a small change. `plex-icon-more-560` now is `plex-icon-more-vertical-560`.

**Comment by cremor** [comment]
Fixed by #46, thanks!
