### ISSUE TITLE
No longer works in Web client Version 3.95.2.

### ISSUE THREAD

**Issue by mambans** [Kayomani/PlexExternalPlayer#34]
The script is running but there are no icons/buttons to click on. Tried on both Firefox and Chrome but none worked.

The issue started today.

Web Client Version 3.95.2 

Plex Media server version: 1.15.4.993-bb4a2cb6c

Would really love an update if possible and if you got time.

**Comment by SashaCrow** [comment]
Kayomani Plz update the script!

**Comment by chocoa510** [comment]
Server version Version 1.15.4.993
Lost the icon and therefore no longer functional, yet tampermonkey script says it has access.
I'm lost without your great work.
Would really appreciate an update to fix this!

**Comment by benlei** [comment]
You can try to replace the script in your Tampermonkey with what I have here: https://github.com/ben-lei/PlexExternalPlayer/blob/master/PlexExternalPlayer.js

Though, I'm not going to update it anymore after I had realized how it works.

**Comment by SashaCrow** [comment]
> You can try to replace the script in your Tampermonkey with what I have here: https://github.com/ben-lei/PlexExternalPlayer/blob/master/PlexExternalPlayer.js


TFX its work well

**Comment by mambans** [comment]
> 
> 
> You can try to replace the script in your Tampermonkey with what I have here: https://github.com/ben-lei/PlexExternalPlayer/blob/master/PlexExternalPlayer.js
> 
> Though, I'm not going to update it anymore after I had realized how it works.

There were no button on the cover pages but it worked once I clicked on the movie/series. A lot better than nothing, thanks! :D

**Comment by LuckyLuke-AT** [comment]
Debugged my way through it and got the buttons on the cover working.

https://github.com/1LucKyLuke/PlexExternalPlayer/blob/master/PlexExternalPlayer.js

**Comment by mambans** [comment]
> 
> 
> Debugged my way through it and got the buttons on the cover working.
> 
> https://github.com/1LucKyLuke/PlexExternalPlayer/blob/master/PlexExternalPlayer.js

It worked! Thanks a lot @1LucKyLuke and @ben-lei !

**Comment by Kayomani** [comment]
I'm too busy with other stuff at the minute but I can accept pull requests
:)

**Comment by chocoa510** [comment]
> Debugged my way through it and got the buttons on the cover working.
> 
> https://github.com/1LucKyLuke/PlexExternalPlayer/blob/master/PlexExternalPlayer.js

That worked. My appreciation for you sharing this @1LucKyLuke @ben-lei  :)

Also, thanks others and to @Kayomani for responding here. :)

**Comment by Kayomani** [comment]
Update posted thanks @1LucKyLuke
