### ISSUE TITLE
Buttons on posters doesn't show on Version 3.108.2.

### ISSUE THREAD

**Issue by mambans** [Kayomani/PlexExternalPlayer#37]
Buttons on the posters doesn't show up anymore since Version 3.108.2.
The buttons in the toolbar still works.

**Comment by enchained** [comment]
You can try to manually replace line in tampermonkey code under // Cover page
`jQuery('[id=plex-icon-more-560]').each(function(i, e) {`
with this one
`jQuery('[id=plex-icon-more-vertical-560]').each(function(i, e) {`

In my case that worked, but my toolbar buttons are missing too, maybe I'll debug that later.
UPD: toolbar is working for me with the most recent script version.

**Comment by mambans** [comment]
Thanks, that worked for me too!

**Comment by Kayomani** [comment]
Send a pull request xD

⁣

**Comment by mambans** [comment]
Just sent it.

Never done a pull request before, so hopes it works.
