### ISSUE TITLE
Wont open flv video

### ISSUE THREAD

**Issue by eseriestv** [Kayomani/PlexExternalPlayer#7]
Hi there,

Thank you for your work. Would you please check why I cant open files with extension .flv I tried several different files, only opens mp4 or other filetypes but flv gives me an error.

The error says:

Tried to load files ...XXXXX but it wasn't allowed

THank you

**Comment by Kayomani** [comment]
I white listed the files it can open for security and flv is missing.  I can add it to the list, might there be any other extensions not covered by the below?

Currently it does:

     if (fn.EndsWith(".avi") ||
                            fn.EndsWith(".mkv") ||
                            fn.EndsWith(".mp4") ||
                            fn.EndsWith(".mpg") ||
                            fn.EndsWith(".ts") ||
                            fn.EndsWith(".mpeg"))

**Comment by eseriestv** [comment]
Good. Where can I add those?

ps. also wmv the same error

**Comment by Kayomani** [comment]
Grab the latest agent release from the release page.
