### ISSUE TITLE
Buttons on Posters

### ISSUE THREAD

**Issue by sym7** [Kayomani/PlexExternalPlayer#8]
Is it possible to toggle the External Player button on posters? Default behavior (without the extension) has the buttons pop up like a toaster, with the extension buttons are always on the poster. It would be nice if the buttons popped up in the original style.

**Comment by Kayomani** [comment]
They aren't always shown for me? There should just be an extra button when pop up on hover.  Are you using Chrome?

**Comment by satsukiyatoshi** [comment]
I'm using firefox (1.9 script version) and the play button is ok in the movies list but not in the movie page:
![epp1](https://cloud.githubusercontent.com/assets/8547498/23964215/0bce88b0-09b4-11e7-9ca7-2015342a7566.jpg)
![epp2](https://cloud.githubusercontent.com/assets/8547498/23964216/0bd17534-09b4-11e7-9779-00b7bee6a8bf.jpg)

**Comment by Kayomani** [comment]
Yes that is intentional as the buttons are on the top right of the page if you have the latest version

**Comment by sym7** [comment]
That's not the same behavior I'm getting. In any library category all the posters show up with these buttons over them, whether I'm hovering over them or not:

![chrome_2017-03-15_15-13-54](https://cloud.githubusercontent.com/assets/6569578/23971132/479cd468-0992-11e7-862e-f8bdc1787670.png)

Happens in both Chrome and Firefox for me.
