### ISSUE TITLE
No more external player icon in movies description since the lastest plex update

### ISSUE THREAD

**Issue by satsukiyatoshi** [Kayomani/PlexExternalPlayer#9]
Hello
Thans for this great script.
Plex sever add a new update for some day witch sligthly change the desing.

I can use plex external player from the moviers list, but in the movie description the plex external player icon doesn't exist anymore.
So if i'm in a movie description, i need to back to the movies list to use plex external player.

Thanks

**Comment by Kayomani** [comment]
I have fixed this in the latest version
